<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="com.setl.RESTAPITests.Account.Creation.createAccountAcceptanceTest" tests="2" skipped="0" failures="2" errors="0" timestamp="2017-12-05T17:32:50" hostname="Bills-iMac.local" time="30.003">
  <properties/>
  <testcase name="createNewAccount" classname="com.setl.RESTAPITests.Account.Creation.createAccountAcceptanceTest" time="30.002">
    <failure message="org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds" type="org.junit.runners.model.TestTimedOutException">org.junit.runners.model.TestTimedOutException: test timed out after 30000 milliseconds
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
	at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:282)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
	at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:165)
	at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
	at com.mashape.unirest.http.HttpClientHelper.request(HttpClientHelper.java:138)
	at com.mashape.unirest.request.BaseRequest.asJson(BaseRequest.java:68)
	at io.setl.restapi.client.RestApi.call(RestApi.java:87)
	at io.setl.restapi.client.RestApi.sendMessage(RestApi.java:67)
	at com.setl.RESTAPITests.Account.Creation.createAccountAcceptanceTest.createNewAccount(createAccountAcceptanceTest.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="failToCreateAccountWithIncorrectPermissions" classname="com.setl.RESTAPITests.Account.Creation.createAccountAcceptanceTest" time="0.001">
    <failure message="java.lang.NullPointerException" type="java.lang.NullPointerException">java.lang.NullPointerException
	at SETLAPIHelpers.RestAPI.AccountHelper.createAccountFailure(AccountHelper.java:64)
	at com.setl.RESTAPITests.Account.Creation.createAccountAcceptanceTest.failToCreateAccountWithIncorrectPermissions(createAccountAcceptanceTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <system-out><![CDATA[payload eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXNzYWdlYm9keSI6eyJ1c2VyaWQiOjR9LCJtZXNzYWdldHlwZSI6ImluaXRpYWxpc2UiLCJyZXF1ZXN0aWQiOjEsInRva2VuIjoiIiwidGltZXN0YW1wIjoxNTEyNDk1MTcwMDM3fQ.Ox4cR2RGc9ifGtf5tLt5okgsmGEObGZaQeRUE1fC3Wc
payload eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJtZXNzYWdlYm9keSI6eyJhY2NvdW50RGVzY3JpcHRpb24iOiJUZXN0X0FjY291bnRfQml4T28iLCJhY2NvdW50TWVtYmVyIjoxLCJhY2NvdW50TmFtZSI6IlRlc3RfQWNjb3VudF9EZXNjX0JpeE9vIiwidG9waWMiOiJuYSJ9LCJtZXNzYWdldHlwZSI6InJlcXVlc3QiLCJyZXF1ZXN0aWQiOjEsInRva2VuIjoiIiwidGltZXN0YW1wIjoxNTEyNDk1MTcwMjM2fQ.GrbH1zyCE0rSGouwqvjGlASjklCDvuyqGYbjVwV7O90
]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
