<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" tests="5" skipped="0" failures="5" errors="0" timestamp="2017-11-28T12:11:59" hostname="Bills-iMac.local" time="0.044">
  <properties/>
  <testcase name="forceUpdateNavPriceWhenNavIsFinalised" classname="src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.004">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.forceUpdateNavPriceWhenNavIsFinalised(NavListUpdateAcceptanceTest.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="UpdateNavFundDate" classname="src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.004">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.UpdateNavFundDate(NavListUpdateAcceptanceTest.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="UpdateNavFundName" classname="src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.005">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.UpdateNavFundName(NavListUpdateAcceptanceTest.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="createNav" classname="src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.024">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.createNav(NavListUpdateAcceptanceTest.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <testcase name="failToUpdateNavPriceWhenNavIsFinalised" classname="src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest" time="0.006">
    <failure message="org.json.JSONException: JSONObject[&quot;jws&quot;] not found." type="org.json.JSONException">org.json.JSONException: JSONObject[&quot;jws&quot;] not found.
	at org.json.JSONObject.get(JSONObject.java:471)
	at io.setl.restapi.client.RestApi.start(RestApi.java:50)
	at src.RESTAPITests.NAV.Update.NavListUpdateAcceptanceTest.failToUpdateNavPriceWhenNavIsFinalised(NavListUpdateAcceptanceTest.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
</failure>
  </testcase>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
